"""show partner and booth employees

Revision ID: 44078d0d3f38
Revises: c607fa44ecef
Create Date: 2021-01-07 16:11:15.657087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44078d0d3f38'
down_revision = 'c607fa44ecef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booth_employees',
    sa.Column('booth_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booth_id'], ['booths.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('booth_id', 'employee_id')
    )
    op.create_table('show_partner_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('booth_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('accepted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['booth_id'], ['booths.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_partner_invites')
    op.drop_table('booth_employees')
    # ### end Alembic commands ###
