"""add booth partners

Revision ID: 657970dffd9e
Revises: c607fa44ecef
Create Date: 2021-01-07 02:46:17.776635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657970dffd9e'
down_revision = 'c607fa44ecef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_partners',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('booth_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booth_id'], ['booths.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('show_id', 'booth_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_partners')
    # ### end Alembic commands ###
