"""initial users

Revision ID: 98890437989f
Revises:
Create Date: 2021-01-06 15:48:30.150518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98890437989f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('card', sa.JSON(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
